	let h = document.getElementById('tt');
	h.innerText = '<p>hello javascript</p>'  
	let ha = document.getElementById('t');
	ha.innerHTML = '<p>hello javascript</p>';
	ha.style.color = "blue";
	ha.style.background = "green";
	ha.style.fontFamily = "cursive";
	ha.style.fontSize = "150px";
	ha.style.padding = "30px";
	let hc = document.getElementById('s');
	hc.style.border = "1px dotted red";
	hc.style.display = "inline";
	hc.innerHTML = "<p>jbd</p>";
	let i = document.getElementById('im')
	i.src = '../images/mountain.avif';
	i.style.backgroundRepeat = "no-repeat";
	i.style.backgroundSize = "cover";
	i.style.backgroundPosition = "center";
	i.style.width = "2000px";
	let ins = document.getElementById('inp');
	ins.value = 'siv';
	ins.style.backgroundColor = "blue";
